// Organization
export const ORGANIZATION_FETCHED = 'ORGANIZATION_FETCHED';

// App
export const APP_LOADING = 'APP_LOADING';

// User
export const USER_FETCHED = 'USER_FETCHED';

export const USER_LOGGED_IN = 'USER_LOGGED_IN';

export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

// Auth ?
export const REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';

export const FAILED_REQUEST = 'AUTH_FAILED_REQUEST';

// Settings
export const LOCALE_SET = 'LOCALE_SET';

// TODO: REMOVE
export const RESET_STATE = 'SETTINGS_RESET_STATE';

export const REQUEST_FAILED = 'SETTINGS_REQUEST_FAILED';
export const REQUEST_LOADING = 'SETTINGS_REQUEST_LOADING';
export const REQUEST_SUCCESS = 'SETTINGS_REQUEST_SUCCESS';
