// User
export const USER_LOGGED_IN = 'USER_LOGGED_IN';

export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

export const REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';

// Auth ?
export const FAILED_REQUEST = 'AUTH_FAILED_REQUEST';

export const LOADING_REQUEST = 'AUTH_LOADING_REQUEST';

// Settings
export const RESET_STATE = 'SETTINGS_RESET_STATE';

export const REQUEST_FAILED = 'SETTINGS_REQUEST_FAILED';
export const REQUEST_LOADING = 'SETTINGS_REQUEST_LOADING';
export const REQUEST_SUCCESS = 'SETTINGS_REQUEST_SUCCESS';
