// User
export const FAILED_REQUEST = 'AUTH_FAILED_REQUEST';

export const LOADING_REQUEST = 'AUTH_LOADING_REQUEST';

export const LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';

export const LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';

export const REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';

// Settings
export const RESET_STATE = 'SETTINGS_RESET_STATE';

export const REQUEST_FAILED = 'SETTINGS_REQUEST_FAILED';
export const REQUEST_LOADING = 'SETTINGS_REQUEST_LOADING';
export const REQUEST_SUCCESS = 'SETTINGS_REQUEST_SUCCESS';
