'use strict';

export const SUPPORTED_JOB_STATUSES = {
	OPEN: 'OPEN',
	ON_HOLD: 'ON_HOLD',
	REOPENED: 'REOPENED',
	SCHEDULED: 'SCHEDULED',
	COMPLETED: 'COMPLETED',
	CANCELLED: 'CANCELLED',
	FOLLOW_UP: 'FOLLOW_UP',
	RESCHEDULED: 'RESCHEDULED',
	IN_PROGRESS: 'IN_PROGRESS',
	PENDING_APPROVAL: 'PENDING_APPROVAL',
	WAITING_FOR_PARTS: 'WAITING_FOR_PARTS',
};

export const SUPPORTED_JOB_PRIORITIES = {
	LOW: 'LOW',
	HIGH: 'HIGH',
	MEDIUM: 'MEDIUM',
	NORMAL: 'NORMAL',
	URGENT: 'URGENT',
};

export const SUPPORTED_JOB_SECTIONS = {
	ALL: 'ALL',
	PENDING: 'PENDING',
	COMPLETE: 'COMPLETE',
	PROCESSING: 'PROCESSING',
};

export default {
	SUPPORTED_JOB_STATUSES,
	SUPPORTED_JOB_SECTIONS,
	SUPPORTED_JOB_PRIORITIES,
}
