export const FAILED_REQUEST = 'USER_FAILED_REQUEST';
export const LOADING_REQUEST = 'USER_LOADING_REQUEST';

export const LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';

export const LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'USER_LOGOUT_FAILED';

export const RESET_STATE = 'USER_RESET_STATE';

export const REQUEST_LOADING = 'USER_REQUEST_LOADING';
export const REQUEST_SUCCESS = 'USER_REQUEST_SUCCESS';
export const REQUEST_FAILED = 'USER_REQUEST_FAILED';
